language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mejdev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mejdev/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-1-620353297607"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SERET_KEY"
